// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BotClient is an autogenerated mock type for the BotClient type
type BotClient struct {
	mock.Mock
}

// SendJoinChannel provides a mock function with given fields: channel
func (_m *BotClient) SendJoinChannel(channel string) error {
	ret := _m.Called(channel)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(channel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendLeaveChannel provides a mock function with given fields: channel
func (_m *BotClient) SendLeaveChannel(channel string) error {
	ret := _m.Called(channel)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(channel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
