// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OrchestratorClient is an autogenerated mock type for the OrchestratorClient type
type OrchestratorClient struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *OrchestratorClient) Close() {
	_m.Called()
}

// JoinChannel provides a mock function with given fields: channel
func (_m *OrchestratorClient) JoinChannel(channel string) {
	_m.Called(channel)
}

// LeaveChannel provides a mock function with given fields: channel
func (_m *OrchestratorClient) LeaveChannel(channel string) {
	_m.Called(channel)
}
