// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorClient interface {
	JoinStream(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (Orchestrator_JoinStreamClient, error)
}

type orchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorClient(cc grpc.ClientConnInterface) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) JoinStream(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (Orchestrator_JoinStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Orchestrator_ServiceDesc.Streams[0], "/Orchestrator/JoinStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &orchestratorJoinStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Orchestrator_JoinStreamClient interface {
	Recv() (*StreamPayload, error)
	grpc.ClientStream
}

type orchestratorJoinStreamClient struct {
	grpc.ClientStream
}

func (x *orchestratorJoinStreamClient) Recv() (*StreamPayload, error) {
	m := new(StreamPayload)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrchestratorServer is the server API for Orchestrator service.
// All implementations must embed UnimplementedOrchestratorServer
// for forward compatibility
type OrchestratorServer interface {
	JoinStream(*EmptyMessage, Orchestrator_JoinStreamServer) error
	mustEmbedUnimplementedOrchestratorServer()
}

// UnimplementedOrchestratorServer must be embedded to have forward compatible implementations.
type UnimplementedOrchestratorServer struct {
}

func (UnimplementedOrchestratorServer) JoinStream(*EmptyMessage, Orchestrator_JoinStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method JoinStream not implemented")
}
func (UnimplementedOrchestratorServer) mustEmbedUnimplementedOrchestratorServer() {}

// UnsafeOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServer will
// result in compilation errors.
type UnsafeOrchestratorServer interface {
	mustEmbedUnimplementedOrchestratorServer()
}

func RegisterOrchestratorServer(s grpc.ServiceRegistrar, srv OrchestratorServer) {
	s.RegisterService(&Orchestrator_ServiceDesc, srv)
}

func _Orchestrator_JoinStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorServer).JoinStream(m, &orchestratorJoinStreamServer{stream})
}

type Orchestrator_JoinStreamServer interface {
	Send(*StreamPayload) error
	grpc.ServerStream
}

type orchestratorJoinStreamServer struct {
	grpc.ServerStream
}

func (x *orchestratorJoinStreamServer) Send(m *StreamPayload) error {
	return x.ServerStream.SendMsg(m)
}

// Orchestrator_ServiceDesc is the grpc.ServiceDesc for Orchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JoinStream",
			Handler:       _Orchestrator_JoinStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/proto/orchestrator.proto",
}
