// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: pkg/proto/orchestrator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamPayload_Type int32

const (
	StreamPayload_JOIN  StreamPayload_Type = 0
	StreamPayload_LEAVE StreamPayload_Type = 1
)

// Enum value maps for StreamPayload_Type.
var (
	StreamPayload_Type_name = map[int32]string{
		0: "JOIN",
		1: "LEAVE",
	}
	StreamPayload_Type_value = map[string]int32{
		"JOIN":  0,
		"LEAVE": 1,
	}
)

func (x StreamPayload_Type) Enum() *StreamPayload_Type {
	p := new(StreamPayload_Type)
	*p = x
	return p
}

func (x StreamPayload_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamPayload_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_orchestrator_proto_enumTypes[0].Descriptor()
}

func (StreamPayload_Type) Type() protoreflect.EnumType {
	return &file_pkg_proto_orchestrator_proto_enumTypes[0]
}

func (x StreamPayload_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamPayload_Type.Descriptor instead.
func (StreamPayload_Type) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_orchestrator_proto_rawDescGZIP(), []int{0, 0}
}

type StreamPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    StreamPayload_Type `protobuf:"varint,1,opt,name=type,proto3,enum=StreamPayload_Type" json:"type,omitempty"`
	Channel string             `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (x *StreamPayload) Reset() {
	*x = StreamPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_orchestrator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPayload) ProtoMessage() {}

func (x *StreamPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPayload.ProtoReflect.Descriptor instead.
func (*StreamPayload) Descriptor() ([]byte, []int) {
	return file_pkg_proto_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *StreamPayload) GetType() StreamPayload_Type {
	if x != nil {
		return x.Type
	}
	return StreamPayload_JOIN
}

func (x *StreamPayload) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type BotJoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BotJoinRequest) Reset() {
	*x = BotJoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_orchestrator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotJoinRequest) ProtoMessage() {}

func (x *BotJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotJoinRequest.ProtoReflect.Descriptor instead.
func (*BotJoinRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_orchestrator_proto_rawDescGZIP(), []int{1}
}

type BotJoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BotJoinResponse) Reset() {
	*x = BotJoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_orchestrator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotJoinResponse) ProtoMessage() {}

func (x *BotJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotJoinResponse.ProtoReflect.Descriptor instead.
func (*BotJoinResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *BotJoinResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_pkg_proto_orchestrator_proto protoreflect.FileDescriptor

var file_pkg_proto_orchestrator_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x63, 0x68,
	0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f,
	0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x27, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x22, 0x1b, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x4f,
	0x49, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x10, 0x01, 0x22,
	0x10, 0x0a, 0x0e, 0x42, 0x6f, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x21, 0x0a, 0x0f, 0x42, 0x6f, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x32, 0x6f, 0x0a, 0x0c, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x0f, 0x2e, 0x42,
	0x6f, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x42, 0x6f, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x32, 0x0a, 0x0a, 0x4a, 0x6f, 0x69, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12,
	0x10, 0x2e, 0x42, 0x6f, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x1a, 0x0e, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x00, 0x30, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_orchestrator_proto_rawDescOnce sync.Once
	file_pkg_proto_orchestrator_proto_rawDescData = file_pkg_proto_orchestrator_proto_rawDesc
)

func file_pkg_proto_orchestrator_proto_rawDescGZIP() []byte {
	file_pkg_proto_orchestrator_proto_rawDescOnce.Do(func() {
		file_pkg_proto_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_orchestrator_proto_rawDescData)
	})
	return file_pkg_proto_orchestrator_proto_rawDescData
}

var file_pkg_proto_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_orchestrator_proto_goTypes = []interface{}{
	(StreamPayload_Type)(0), // 0: StreamPayload.Type
	(*StreamPayload)(nil),   // 1: StreamPayload
	(*BotJoinRequest)(nil),  // 2: BotJoinRequest
	(*BotJoinResponse)(nil), // 3: BotJoinResponse
}
var file_pkg_proto_orchestrator_proto_depIdxs = []int32{
	0, // 0: StreamPayload.type:type_name -> StreamPayload.Type
	2, // 1: Orchestrator.Join:input_type -> BotJoinRequest
	3, // 2: Orchestrator.JoinStream:input_type -> BotJoinResponse
	3, // 3: Orchestrator.Join:output_type -> BotJoinResponse
	1, // 4: Orchestrator.JoinStream:output_type -> StreamPayload
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_orchestrator_proto_init() }
func file_pkg_proto_orchestrator_proto_init() {
	if File_pkg_proto_orchestrator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_orchestrator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_orchestrator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotJoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_orchestrator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotJoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_orchestrator_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_orchestrator_proto_goTypes,
		DependencyIndexes: file_pkg_proto_orchestrator_proto_depIdxs,
		EnumInfos:         file_pkg_proto_orchestrator_proto_enumTypes,
		MessageInfos:      file_pkg_proto_orchestrator_proto_msgTypes,
	}.Build()
	File_pkg_proto_orchestrator_proto = out.File
	file_pkg_proto_orchestrator_proto_rawDesc = nil
	file_pkg_proto_orchestrator_proto_goTypes = nil
	file_pkg_proto_orchestrator_proto_depIdxs = nil
}
